
graphql:
  playground:
    enabled: true
    cdn:
      enabled: false
  tools:
    schema-location-pattern: '**/*.graphql'

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL:jdbc:mariadb://localhost:3306/blog}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

#logging:
#  level:
#    org.hibernate.SQL: debug

security:
  secret-key: secret-key
  auth-token-expire: 1800000
  refresh-token-expire: 10080000

storage:
  path: ${STORAGE:./Storage/}

server:
  port: 8888

logging:
  level:
    com.yoonleeverse.blog: debug
