
graphql:
  playground:
    enabled: true
    cdn:
      enabled: false
  tools:
    schema-location-pattern: '**/*.graphql'

spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_USERNAME}

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  jackson:
    property-naming-strategy: SNAKE_CASE

#logging:
#  level:
#    org.hibernate.SQL: debug

security:
  secret-key: secret-key
  auth-token-expire: 1800000
  refresh-token-expire: 10080000

storage:
  path: ${STORAGE_PATH}

server:
  port: 8000
